name: challenge2

env:
    workspace_varialbe: warehouse_management

on: push

jobs:
  cha1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2.3.0

      - name: create a artifacts
        run: touch ${{ env.workspace_varialbe }}

      - name: upload artifacts
        uses: actions/upload-artifact@v2.2.1
        with:
          name: generated_artifact
          path: ./${{ env.workspace_varialbe }} 
  
  cha2:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2.3.0
        
      - name: download the artifacts
        uses: actions/download-artifact@v2.0.7
        with:
           name: generated_artifact
            
      - name: rename the artifactcs
        run: mv ${{ env.workspace_varialbe }} renamed_version
        
      - name: upload renamed artifactcs
        uses: actions/upload-artifact@v2.2.1
        with:
          name: renamed_artifacts
          path: renamed_version
      
        
    
      
      
    
          
          
        



    

