name: challenge2

env:
    workspace_varialbe: warehouse_management

on: push

jobs:
  cha1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2.3.4

      - name: create a artifacts
        run: touch ${{ env.workspace_varialbe }}

      - name: upload artifacts
        uses: actions/upload-artifact@v2.2.1
        with:
          name: generated_artifact
          path: ./${{ env.workspace_varialbe }} 
          
          
        



    

